# Generated by Django 3.2 on 2021-05-02 09:07

import KnoxApp1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=250)),
                ('blogImage', models.ImageField(upload_to='')),
                ('blogContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=50)),
                ('bike_company', models.CharField(max_length=50)),
                ('bike_model', models.CharField(max_length=50)),
                ('bike_color', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('kmcovered', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=500)),
                ('completed', models.CharField(default='Not Completed', max_length=100)),
                ('serviceDate', models.DateField(validators=[KnoxApp1.models.ServiceRequestForm.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('bike_number', models.CharField(max_length=50)),
                ('bike_color', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnoxApp1.bikecompanymodel', to_field='companyName')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
