# Generated by Django 3.2 on 2021-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnoxApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestform',
            name='deliveryTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicerequestform',
            name='serviceTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
