# Generated by Django 3.2 on 2021-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnoxApp1', '0002_auto_20210502_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestform',
            name='deliveryTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servicerequestform',
            name='serviceTime',
            field=models.TimeField(),
        ),
    ]
