# Generated by Django 3.2 on 2021-05-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnoxApp1', '0003_auto_20210502_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blogTitle',
            field=models.CharField(max_length=500),
        ),
    ]
