# Generated by Django 3.2 on 2021-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnoxApp1', '0004_auto_20210504_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=255)),
                ('serviceContent', models.TextField()),
                ('servicePhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
