# Generated by Django 3.2 on 2021-05-10 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KnoxApp1', '0007_alter_extenderuser_phone_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extenderUser',
            new_name='Profile',
        ),
    ]
